---
title: "co2"
author: "James Eager"
date: "`r Sys.Date()`"
output: 
  tufte::tufte_handout: default
editor_options: 
  chunk_output_type: console
---

```{r include = FALSE, echo = FALSE}
rm(list = ls())
```

```{r setup, include=FALSE}
library(tufte)
# invalidate cache when the tufte version changes
knitr::opts_chunk$set(cache.extra = packageVersion('tufte'))
options(htmltools.dir.version = FALSE)

library(tidyverse)
library(ggrepel)
library(RColorBrewer)
library(ggthemes)
library(ggExtra)
library(viridis)
library(scales)
library(readxl)
library(kableExtra)
library(lubridate)
library(sf)
library(tufte)
library(ggspatial)
library(mapboxapi)
library(leaflet)
library(tidycensus)
library(tigris)
library(showtext)
library(factoextra)

knitr::opts_chunk$set(echo = FALSE, include = FALSE, message = FALSE)
options(knitr.table.format = "latex")
options(tigris_use_cache = TRUE)
wdt = 7.25
hgt = wdt/1.62
bs= 10
capt = paste0("Source: PHMSA Incident and Mileage Data (",
              lubridate::year(Sys.Date()),
              ")")
datadir = "https://raw.githubusercontent.com/jmceager/pst/main/phmsa-clean/data/"
tag = paste("PST", lubridate::year(Sys.Date()))

pstFont = "Montserrat"
font_add_google(pstFont)
showtext_opts(dpi=300) 
showtext_auto()# theme clean adjustments to apply to ggplot

extrafont::font_import("/Users/jameseager/Library/Fonts/")

setwd("/Users/jameseager/Documents/pst/research/lookups/co2")

```

```{r theme_pst}
#### main plot theme ####
theme_pst <- function(baseSize=bs) {
  (theme(
                       axis.line.x = element_line(
                         colour = "#182125",
                         linewidth = 0.5,
                         linetype = "solid"
                       ),
                       axis.line.y = element_line(
                         colour = "#182125",
                         linewidth = 0.5,
                         linetype = "solid"
                       ),
                       axis.ticks.y = element_line(
                         colour = "#182125",
                         linewidth = 0.5,
                         linetype = "solid"
                       ),
                       text = element_text(family = pstFont),
                       axis.text = element_text(colour = "#8C9394",
                                                size = baseSize * .8),
                       axis.title = element_text(colour ="black", 
                                                 size= baseSize),
                       panel.grid.minor.y = element_line(linetype = "dotted", 
                                                         colour = "#C4C8C6"),
                       panel.grid.major.y = element_line(colour = "#394C56", 
                                                         linetype = "dotted"),
                       panel.grid.major.x = element_blank(),
                       panel.grid.minor.x = element_blank(),
                       panel.background = element_blank(),
                       panel.border = element_blank(),
                       strip.background = element_rect(linetype = 0),
                       strip.text = element_blank(),
                       strip.text.x = element_blank(),
                       strip.text.y = element_blank(),
                       legend.text = element_text(colour = "black",
                                                  size = baseSize * .8),
                       legend.background = element_rect(fill = NULL, 
                                                        color = "#182125"),
                       legend.title = element_text( face = "bold", 
                                                    colour = "black",
                                                    size = baseSize),
                       legend.position = "right",
                       legend.key = element_blank(),
                       legend.spacing.y = unit(.125, 'cm'),
                       #legend.background = element_blank(),
                       plot.tag.location = "plot",
                       plot.title.position = "plot",
                       plot.tag.position = "topright",
                       plot.tag = element_text(size = baseSize *.66,
                                               colour = "#8C9394"),
                       plot.background = element_rect(fill = "#ffffff"),
                       plot.title = element_text(face = "bold", 
                                                 colour = "black",
                                                 size = baseSize*1.2),
                       plot.subtitle = element_text(colour = "#8C9394",
                                                    size = baseSize),
                       plot.caption = element_text(size = baseSize *.8)
                     )
  )
}



#### map theme ####
theme_pst_map <- function(baseSize=bs) {
  (theme_void() + 
     theme(
       legend.direction = "horizontal",
       legend.position = "bottom",
       plot.tag.location = "plot",
       plot.title.position = "plot",
       plot.tag.position = "topright",
       text = element_text(family = pstFont),
       legend.text = element_text(colour = "black",
                                   size = baseSize * .8),
       legend.background = element_rect(fill = NA, 
                                        color = NA),
       legend.title = element_text( face = "bold", 
                                    colour = "black",
                                    size = baseSize),
       legend.key = element_blank(),
       plot.background = element_rect(fill = "#ffffff", colour = NA),
       plot.margin = unit(c(0,0,0,0), "cm"),
       plot.tag = element_text(size = baseSize *.66,
                               colour = "#8C9394"),
       plot.title = element_text(face = "bold", 
                                 colour = "black",
                                 size = baseSize*1.2),
       plot.subtitle = element_text(colour = "#8C9394",
                                    size = baseSize),
       plot.caption = element_text(size = baseSize *.8,
                                   lineheight = .33)
       )

                    
  )
}

#### flip theme ####
theme_pst_flip <- function(baseSize=bs) {
  (theme(
                       axis.line.y = element_line(
                         colour = "#182125",
                         linewidth = 0.5,
                         linetype = "solid"
                       ),
                       axis.line.x = element_line(
                         colour = "#182125",
                         linewidth = 0.5,
                         linetype = "solid"
                       ),
                       axis.ticks.y = element_line(
                         colour = "#182125",
                         linewidth = 0.5,
                         linetype = "solid"
                       ),
                       text = element_text(family = pstFont),
                       axis.text = element_text(colour = "#8C9394",
                                                size = baseSize * .8),
                       axis.title = element_text(colour ="black", 
                                                 size= baseSize),
                       panel.grid.minor.x = element_line(linetype = "dotted", 
                                                         colour = "#C4C8C6"),
                       panel.grid.major.x = element_line(colour = "#394C56", 
                                                         linetype = "dotted"),
                       panel.grid.major.y = element_blank(),
                       panel.grid.minor.y = element_blank(),
                       panel.background = element_blank(),
                       panel.border = element_blank(),
                       strip.background = element_rect(linetype = 0),
                       strip.text = element_blank(),
                       strip.text.x = element_blank(),
                       strip.text.y = element_blank(),
                       legend.text = element_text(colour = "black",
                                                  size = baseSize * .8),
                       legend.background = element_rect(fill = NULL, 
                                                        color = "#182125"),
                       legend.title = element_text( face = "bold", 
                                                    colour = "black",
                                                    size = baseSize),
                       legend.position = "right",
                       legend.key = element_blank(),
                       #legend.background = element_blank(),
                       plot.tag.location = "plot",
                       plot.title.position = "plot",
                       plot.tag.position = "topright",
                       plot.tag = element_text(size = baseSize *.66,
                                               colour = "#8C9394"),
                       plot.background = element_rect(fill = "#ffffff"),
                       plot.title = element_text(face = "bold", 
                                                 colour = "black",
                                                 size = baseSize*1.2),
                       plot.subtitle = element_text(colour = "#8C9394",
                                                    size = baseSize),
                       plot.caption = element_text(size = baseSize *.8)
                     )
  )
}

#### facet theme ####
theme_pst_facet <- function(baseSize=bs) {
  (theme(
                       axis.line.x = element_line(
                         colour = "#182125",
                         linewidth = 0.5,
                         linetype = "solid"
                       ),
                       axis.line.y = element_line(
                         colour = "#182125",
                         linewidth = 0.5,
                         linetype = "solid"
                       ),
                       axis.ticks.y = element_line(
                         colour = "#182125",
                         linewidth = 0.5,
                         linetype = "solid"
                       ),
                       text = element_text(family = pstFont),
                       axis.text = element_text(colour = "#8C9394",
                                                size = baseSize * .8),
                       axis.title = element_text(colour ="black", 
                                                 size= baseSize),
                       panel.grid.minor.y = element_line(linetype = "dotted", 
                                                         colour = "#C4C8C6"),
                       panel.grid.major.y = element_line(colour = "#394C56", 
                                                         linetype = "dotted"),
                       panel.grid.major.x = element_blank(),
                       panel.grid.minor.x = element_blank(),
                       panel.border = element_blank(),
                       strip.background = element_rect(linetype = 0),
                       strip.text = element_blank(),
                       strip.text.x = element_text(colour = "gray15",
                                                  size = baseSize * .8,
                                                  margin = ),
                       strip.text.y = element_text(colour = "gray15",
                                                  size = baseSize * .8),
                       legend.text = element_text(colour = "black",
                                                  size = baseSize * .8),
                       legend.background = element_rect(fill = NULL, 
                                                        color = "#182125"),
                       legend.title = element_text( face = "bold", 
                                                    colour = "black",
                                                    size = baseSize),
                       legend.position = "right",
                       legend.key = element_blank(),
                       legend.spacing.y = unit(.125, 'cm'),
                       #legend.background = element_blank(),
                       plot.tag.location = "plot",
                       plot.title.position = "plot",
                       plot.tag.position = "topright",
                       plot.tag = element_text(size = baseSize *.66,
                                               colour = "#8C9394"),
                       plot.background = element_rect(fill = "#ffffff"),
                       panel.background = element_rect(fill = "#f1f3f4"),
                       plot.title = element_text(face = "bold", 
                                                 colour = "black",
                                                 size = baseSize*1.2),
                       plot.subtitle = element_text(colour = "#8C9394",
                                                    size = baseSize),
                       plot.caption = element_text(size = baseSize *.8)
                     )
  )
}


```

```{r nice colors}
#brewer pal
col <- brewer.pal(6,"Set2")
green <- col[1]
orange <- col[2]
purple <- col[3]
pink <- col[4]
lime <- col[5]
yellow <- col[6]

ecru = "#FFEEDB"


#pst 
darkBlue <- "#003E59"
midBlue <- "#00546F"
bluGreen <- "#459197"
liteGreen <- "#61A893"

richblk <- "#182125"


#pst contrast 
#1
honey <- "#F2AA18"
lilac <- "#C297B8"
# 2
hunterGrn <- "#315C2B"
maize <- "#E7BB41"

crimson <- "#96140D"
lavBlu <- "#C6CAED"

#based on pst
liteBlue <- "#5CCEFF"
liteBlu2 <- "#0AC2FF"
darkGreen <- "#3C685A"
brown <- "#664400"

## coolors
purp = "#644695"

# pst pairs
blu_p = "#A8E5FF"
crim_p = "#F27069"
purp_p = "#9E86C6"
lil_p = "#673C5D"
green_p1 = "#3E7061"
green_p2 = "#90C2B3"
ecru_p = "#241300"


#pals 
pst1 <- c(darkBlue, liteGreen, lilac, honey, bluGreen, crimson)
pst2 <- c(darkBlue, liteGreen, lilac, brown, maize, midBlue)
pstMax <- c(darkBlue, liteGreen, lilac, honey, purp, brown, crimson, liteBlu2)
pstPaired <- c(darkBlue, blu_p, green_p1, green_p2, lilac, lil_p, 
               crimson, crim_p, ecru_p, ecru)


pstRep <- c(
  CO2 = honey,
  `Crude Oil` = darkBlue,
  `Fuel Grade Ethanol` = brown,
  HVL = lilac,
  `Petrol Product (non-HVL)` = liteGreen
)

```


```{r incident data}
#get df
#remove outer continental shelf incidents 
df <- read_csv(paste0(datadir, "clean/all_inc.csv") ) 

#join, including transformation from wgs84 to nad 83
df_sp <- df %>%
  st_as_sf(coords = c("LOCATION_LONGITUDE", "LOCATION_LATITUDE"), crs = 4326)%>%
  st_transform(2229)


hl <- read_csv(paste0(datadir, "clean/hl_inc.csv") )

```

```{r getting annual report data}

## read ar part H csvs <-
#read following cols 
# OPERATOR_ID, INTER_INTRA, PARTHONNTOTAL


 # set to location of annual reports 

#setwd("/Users/jameseager/Documents/pst/research/state-transparency/data/reports") # set to location of annual reports 


liqAR <- plyr::ldply(.data = list.files(pattern = "hazardous_liquid",
                                        path = "/Users/jameseager/Downloads/annual_hazardous_liquid_2010_present/",
                                        full.name = T),
               .fun = read_xlsx,
               skip = 2
               )

# setwd("./old")
# 
# liqAROld <- ldply(.data = list.files(pattern = "_liquid_"),
#                   .fun = read.csv
#                   )
# 
# gtrAROld <- ldply(.data = list.files(pattern = "_transmission_"),
#                   .fun = read.csv
#                   )
#    
#setwd("/Users/jameseager/Documents/pst/research/lookups/operators")

```

```{r}
# gt_ar <- read_xlsx("/Users/jameseager/Downloads/annual_gas_transmission_gathering_2010_present/annual_gas_transmission_gathering_2023.xlsx", skip = 2)

hl_ar <- read_xlsx("/Users/jameseager/Downloads/annual_hazardous_liquid_2010_present/annual_hazardous_liquid_2022.xlsx", skip = 2)

hl_ar3 <- read_xlsx("/Users/jameseager/Downloads/annual_hazardous_liquid_2010_present/annual_hazardous_liquid_2022.xlsx", skip = 2, sheet =4)

```

```{r}
 liqAR3 <- plyr::ldply(.data = list.files(pattern = "hazardous_liquid",
                                        path = "/Users/jameseager/Downloads/annual_hazardous_liquid_2010_present/",
                                        full.name = T),
               .fun = read_xlsx,
               skip = 2,
               sheet = 4
               )

state_sum <- liqAR3 %>%
  filter(REPORT_YEAR >= 2014)%>%
  left_join(com_names)%>%
  filter(new_names == "CO2")%>%
  group_by(REPORT_YEAR, STATE_NAME)%>%
  summarize(miles = sum(PARTITOTAL,na.rm = T)) %>% 
  bind_rows(
    liqAR3 %>%
      filter(REPORT_YEAR >= 2022)%>%
      left_join(com_names)%>%
      filter(new_names == "CO2")%>%
      group_by(REPORT_YEAR, STATE_NAME)%>%
      summarize(miles = sum(PARTITOTAL,na.rm = T)) %>% 
      mutate(REPORT_YEAR = 2023)
  )%>%
  ungroup()%>%
  complete(STATE_NAME, REPORT_YEAR, fill = list(miles = 0))%>%
  left_join(
    hl %>%
      count(IYEAR, STATE)%>%
      mutate(STATE_NAME = str_to_upper(state.name[match(STATE, state.abb)])) ,
    by = c("STATE_NAME", "REPORT_YEAR" = "IYEAR")
  )%>%
  mutate(ipm = n / miles)%>% 
  ungroup()%>%
  group_by(STATE_NAME, STATE)%>%
  summarize(min = miles[REPORT_YEAR == 2014],
            max = miles[REPORT_YEAR == 2023],
            inc = sum(n),
            n = n(),
            ipm = mean(ipm[miles>0], na.rm = T)) 
```



```{r eval = F}
hl %>% 
  filter(between(IYEAR, 2010, 2023),
         ON_OFF_SHORE == "ONSHORE")%>%
  filter(COMMODITY_RELEASED_TYPE == "CO2 (CARBON DIOXIDE)")%>%
  count(ACCIDENT_IDENTIFIER) %>% 
  mutate(total = sum(n, na.rm = T),
         per = n / total) 

hl %>% 
  filter(between(IYEAR, 2010, 2023),
         ON_OFF_SHORE == "ONSHORE")%>%
  count(ACCIDENT_IDENTIFIER) %>% 
  mutate(total = sum(n, na.rm = T),
         per = n / total) %>% view

hl %>% 
  filter(between(IYEAR, 2010, 2023),
         ON_OFF_SHORE == "ONSHORE")%>%
  filter(COMMODITY_RELEASED_TYPE == "CO2 (CARBON DIOXIDE)")%>%
  count(IYEAR)

hl %>%
  filter(between(IYEAR, 2018, 2023),
         ON_OFF_SHORE == "ONSHORE")%>%
  filter(!is.na(ON_SITE_DATETIME))%>%
  mutate(onsitediff = seconds_to_period( ON_SITE_DATETIME - INCIDENT_IDENTIFIED_DATETIME) ,
         shutdowninc = seconds_to_period(SHUTDOWN_DATETIME - LOCAL_DATETIME),
         shutdowndiff = seconds_to_period(SHUTDOWN_DATETIME - INCIDENT_IDENTIFIED_DATETIME)) %>%
  #filter(COMMODITY_RELEASED_TYPE == "CO2 (CARBON DIOXIDE)")%>%
  select(MDY, NAME.x,cleanLoc, ON_SITE_DATETIME, SHUTDOWN_DATETIME,
         INCIDENT_IDENTIFIED_DATETIME, ACCIDENT_IDENTIFIER,
         ACCIDENT_DETAILS, COMMODITY_RELEASED_TYPE,
         #ends_with("DATETIME"),
         TOTAL_RELEASE, onsitediff, shutdowndiff, shutdowninc)%>% #view
  select(COMMODITY_RELEASED_TYPE,INCIDENT_IDENTIFIED_DATETIME, SHUTDOWN_DATETIME,onsitediff, shutdowndiff, shutdowninc) %>%
  # filter(!is.na(onsitediff))%>%
 # filter(onsitediff >= seconds(0),
 #        shutdowndiff >= seconds(0)) %>%
  mutate(onsitediff = period_to_seconds(onsitediff),
         shutdowndiff = period_to_seconds(shutdowndiff)) %>% 
 # filter(shutdowndiff <= hours(2)) %>% #view
  #summary()
group_by(COMMODITY_RELEASED_TYPE) %>%
  summarize(diffmu = seconds_to_period(mean(onsitediff, na.rm = T)),
            diff2mu =seconds_to_period(mean(shutdowndiff, na.rm = T)),
            diffsd = sd(onsitediff, na.rm = T),
            diff2sd = sd(shutdowndiff, na.rm = T),
            range = seconds_to_period(range(shutdowndiff, na.rm = T)),
            max = seconds_to_period(max(shutdowndiff, na.rm = T)),
            maxs = max(shutdowndiff,na.rm =T)) %>% view




```

6
```{r}
com_names <- tibble(
  PARTA5COMMODITY = sort(unique(liqAR$PARTA5COMMODITY))[c(3,1,2,4,5)],
  COMMODITY_RELEASED_TYPE = sort(unique(hl$COMMODITY_RELEASED_TYPE)),
  new_names = c("Fuel Grade Ethanol", "CO2", "Crude Oil", "HVL", "Petrol Product (non-HVL)")
)



```

#national trends

```{r miles over time }
#setwd("research/lookups/co2")

liqAR %>%
  group_by(REPORT_YEAR, PARTA5COMMODITY) %>%
  summarise(miles = sum(PARTDTOTALMILES, na.rm = T)) %>%
  left_join(com_names)%>%
  #group_by(REPORT_YEAR) %>% mutate(total = sum(miles))%>% ungroup()%>% mutate(per = miles/total)%>% view
  ggplot(aes(x = REPORT_YEAR, y = miles, col = new_names))+
  geom_line(show.legend = F, linewidth = .8)+
  geom_text(aes(label = str_wrap(new_names, 16), x = 2022.1),
            data = . %>% filter(REPORT_YEAR == 2022),
            show.legend = F, hjust = 0, vjust = 0, lineheight = .66)+
  scale_color_manual(values = pstRep)+
  scale_x_continuous(limits = c(2010, 2022), expand = c(0,0),
                     breaks = seq(2010,2022,2),
                     oob = function(x, ...) x)+
  scale_y_continuous(limits = c(0,90000), expand = c(0,0), 
                     labels = scales::label_number(scale = .001, suffix = "K"))+
  coord_cartesian(clip="off")+
  theme_pst()+
  theme(plot.margin = margin(3,30,3,4, "mm"),
        plot.tag.location = "plot")+
  labs(y = NULL, x=NULL, title = "Hazardous Liquid Pipeline Mileage by Commodity",
       caption = "PHMSA Annual Reports, Hazardous Liquids 2010-2022",
       tag = tag)

ggsave("plots/commodity_miles.png", width = wdt, height = hgt)


liqAR %>%
  filter(grepl("Ethanol",PARTA5COMMODITY))%>%
  group_by(REPORT_YEAR, PARTA5COMMODITY) %>%
  summarise(miles = sum(PARTDTOTALMILES, na.rm = T))%>%
  ggplot(aes(x = REPORT_YEAR, y = miles))+
  geom_line(show.legend = F, linewidth = .8, col = brown)+
  scale_x_continuous(limits = c(2010, 2022), expand = c(0,0),
                     oob = function(x, ...) x)+
  scale_y_continuous(limits = c(0,21), expand = c(0,0), 
                     labels = scales::label_number())+
  theme_pst(12)+
  theme(panel.grid.minor.y = element_blank())+
  labs(x = NULL, y = NULL, tag = tag)

ggsave("plots/fuel_ethanol.png", width = 3, height = 3/1.62)

```

```{r}
liqAR %>%
  group_by(REPORT_YEAR, PARTA5COMMODITY) %>%
  summarise(miles = sum(PARTDTOTALMILES, na.rm = T),
            hca = sum(PARTBHCATOTAL, na.rm =T)) %>% 
  left_join(com_names)%>%
  # view
  ggplot(aes(x = reorder(new_names, hca/miles), y = hca/miles, fill = new_names))+
  geom_bar(show.legend = F,stat = "identity", width = .7,
           data = . %>% filter(REPORT_YEAR == 2022))+
  scale_fill_manual(values = pstRep)+
  scale_y_continuous(limits = c(0,1), expand = c(0,0), 
                     labels = scales::label_percent(accuracy = 1))+
  scale_x_discrete(labels = function(x) str_wrap(x,16))+
  coord_flip(clip="off")+
  theme_pst_flip()+
  theme(plot.margin = margin(3,30,3,4, "mm"))+
  labs(y = "% of Mileage 'Could be HCA'",x=NULL, title = "Hazardous Liquid HCA Mileage Proportion by Commodity", tag = tag,
       caption = "PHMSA Annual Reports, Hazardous Liquids 2022")

ggsave("plots/hca_comm_miles.png", width = wdt, height = hgt)
  
```


```{r giving ar a 2023 using 2022 data}
liqAR_fix <- liqAR %>%
  rbind(
    liqAR %>% filter(REPORT_YEAR == 2022) %>%
      mutate(REPORT_YEAR = 2023)
  )


```

```{r}
hl_ar3 %>%
  group_by(STATE_NAME, PARTA5COMMODITY)%>%
  summarize(miles = sum(PARTITOTAL, na.rm = T))%>% view
```


```{r big map tings}
us_states <- tigris::states()

# need appropriate projections for the lower 48 states, for Alaska, and for Hawaii
# ESRI:102003
crs_lower48 <- "+proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=37.5 +lon_0=-96 +x_0=0 +y_0=0 +ellps=GRS80 +datum=NAD83 +units=m +no_defs"
# EPSG:3338
crs_alaska <- "+proj=aea +lat_1=55 +lat_2=65 +lat_0=50 +lon_0=-154 +x_0=0 +y_0=0 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs "
# ESRI:102007
crs_hawaii <- "+proj=aea +lat_1=8 +lat_2=18 +lat_0=13 +lon_0=-157 +x_0=0 +y_0=0 +ellps=GRS80 +datum=NAD83 +units=m +no_defs"

# convert to sf and project
us_states <- us_states %>%
  st_transform(crs_lower48) %>%
  filter(!STATEFP %in% c("60", "72","66","69","78")) # remove Puerto Rico

# now remove Alaska and Hawaii for lower 48, and calculate bounding box
us_lower48 <- filter(us_states, !STATEFP %in% c("02", "15"))
bb <- st_bbox(us_lower48)


# to move Alaska and Hawaii, we need a helper function that can place an SF geometry object
# at a desired position and scale; the scale option is not used in this code example
place_geometry <- function(geometry, position, scale = 1) {
  (geometry - st_centroid(geometry)) * scale +
    st_sfc(st_point(position))
}

# move Alaska
us_alaska <- filter(us_states, STATEFP == "02")
us_alaska2 <- st_transform(us_alaska, crs_alaska)
st_geometry(us_alaska2) <- place_geometry(
  st_geometry(us_alaska2),
  c(bb$xmin - 0*(bb$xmax - bb$xmin),
    bb$ymin - 0*(bb$ymax - bb$ymin))
)
# we're cheating here by assigning a projection that isn't correct; we
# need to do this because the final compound map needs to have a single
# projection
st_crs(us_alaska2) <- crs_lower48

# move Hawaii
us_hawaii <- filter(us_states, STATEFP == "15")
us_hawaii2 <- st_transform(us_hawaii, crs_hawaii)
st_geometry(us_hawaii2) <- place_geometry(
  st_geometry(us_hawaii2),
  c(bb$xmin + 0.3*(bb$xmax - bb$xmin),
    bb$ymin + 0.*(bb$ymax - bb$ymin))
)
# cheating, as before
st_crs(us_hawaii2) <- crs_lower48

# now make four data frames:
# 1. original map
# 2. map with Hawaii moved
# 3. map with Hawaii and Alaska moved
# 4. like 3, to generate an additional state in gganimate
# we use prefixes "a_", "b_", etc in the `type` variable as a
# simple cheat to get the animation order right in gganimate

new_states<- rbind(us_lower48, us_alaska2, us_hawaii2)

bb2 <- st_bbox(new_states)
```

```{r}
state_co2 <- hl_ar3 %>%
  left_join(com_names)%>%
  group_by(STATE_NAME, new_names)%>%
  summarize(miles = sum(PARTITOTAL, na.rm = T))%>%
  group_by(STATE_NAME)%>%
  mutate(total = sum(miles))%>%
  ungroup()%>%
  mutate(mi_per = miles/total)%>%
  filter(new_names == "CO2")%>%
  mutate(NAME = str_to_title(STATE_NAME)) %>%
  right_join(new_states) %>%
  left_join(
    state_sum,
    by =c("STUSPS" = "STATE")
  ) %>%
  mutate(change = (max-min) / min)




ggplot()+
  layer_spatial(data=state_co2, aes(fill = miles), color = "#f2f2f2")+
  scale_fill_gradient(low = muted(liteGreen, l = 95, c = 3), 
                    high = midBlue, limits = c(0,1863), 
                    labels = scales::label_comma(), 
                    name = NULL, breaks = c(600,1200, 1800),
                    na.value = "#9EA6A9")+
  theme_pst_map()+
  theme(legend.position = "inside",
        legend.position.inside = c(.8,.1))+
  labs(title = "Miles of CO2 Pipeline by State", tag = tag,
       caption = capt)
ggsave("plots/miles_state.png", width = wdt, height = hgt)



ggplot()+
  layer_spatial(data=state_co2, aes(fill = mi_per), color = "#f2f2f2")+
  scale_fill_gradient(low = muted(liteGreen, l = 95, c = 3), 
                    high = midBlue, limits = c(0,.15), 
                    labels = scales::label_percent(), 
                    name = NULL, breaks = c(.05,.1,.15),
                    na.value = "#9EA6A9")+
  theme_pst_map()+
  theme(legend.position = "inside",
        legend.position.inside = c(.8,.1))+
  labs(title = "Proportion of CO2 Pipelines in HL System by State",tag = tag,
       caption = capt)

ggsave("plots/permi_state.png", width = wdt, height = hgt)


ggplot()+
  layer_spatial(data=state_co2, aes(fill = ipm), color = "#f2f2f2")+
  scale_fill_gradient(low = muted(liteGreen, l = 95, c = 3), 
                    high = midBlue, #limits = c(0,.7), 
                   # labels = scales::label_percent(), 
                    name = NULL, #breaks = c(.2,.4,.6),
                    na.value = "#9EA6A9")+
  theme_pst_map()+
  theme(legend.position = "inside",
        legend.position.inside = c(.8,.1))+
  labs(title = "Average Incident Rate of CO2 Pipelines by State",tag = tag,
       caption = capt)
ggsave("plots/ipm_state.png", width = wdt, height = hgt)


# 
# ggplot()+
#   layer_spatial(data=state_co2, aes(fill = ifelse(change>1,1,change)), color = "#f2f2f2")+
#   scale_fill_gradient2(low = honey, mid = "#FFEEDB" ,
#                     high = midBlue, limits = c(-1,1), 
#                     breaks = seq(-1,1,.5),
#                     labels = c("-100%", "-50%", "0%", "50%", "≥100%"),
#                     midpoint = 0,name = NULL,
#                     na.value = "#9EA6A9")+
#   theme_pst_map()+
#   theme(legend.position = "inside",
#         legend.position.inside = c(.8,.1))+
#   labs(title = "Proportion of CO2 Pipelines in HL System by State")
```


```{r}
hl_summary <- hl %>%
  filter(between(IYEAR, 2014,2023))%>%
  group_by(COMMODITY_RELEASED_TYPE, IYEAR) %>%
  summarize(n = n(),
            sig = sum(SIGNIFICANT == "YES", na.rm = T),
            hca = sum(COULD_BE_HCA == "YES", na.rm = T),
            rel = sum(TOTAL_RELEASE, na.rm = T),
            cost = sum(TOTAL_COST_CURRENT, na.rm = T),
            fatal = sum(FATAL, na.rm = T),
            injure = sum(INJURE, na.rm = T))%>%
  ungroup()%>%
  complete(COMMODITY_RELEASED_TYPE, IYEAR, fill = list(n = 0, hca = 0, sig = 0,
                                                       rel = 0, cost = 0,
                                                       fatal = 0, injure = 0))%>%
  left_join(com_names)%>% 
  left_join(
    liqAR_fix %>%
      filter(between(REPORT_YEAR, 2014,2023))%>%
      group_by(PARTA5COMMODITY, REPORT_YEAR)%>%
      summarize(miles = sum(PARTDTOTALMILES, na.rm = T),
                hca_miles = sum(PARTBHCATOTAL, na.rm = T)),
    by = c("IYEAR" = "REPORT_YEAR", "PARTA5COMMODITY" = "PARTA5COMMODITY")
  ) %>% 
  # mutate(rate = n/miles,
  #        hca_rate = hca / hca_miles#,
  #        #across(rel:injure, ~.x/n, .names = "{.col}_per")
  #        )%>% 
  group_by(new_names) %>%
  summarize(across(n:injure, ~sum(.x,na.rm = T)),
            inc_per = sum(n)/(sum(miles)/1000),
            sinc_per = sum(sig)/ (sum(miles)/1000),
            hci_per = sum(hca)/(sum(hca_miles)/1000))%>%
  ungroup()%>%
  mutate(across(sig:injure, ~.x/n, .names = "{.col}_per"))


```


```{r sig inc rate}
hl %>%
  filter(between(IYEAR, 2014,2023))%>%
  group_by(COMMODITY_RELEASED_TYPE, IYEAR) %>%
  summarize(n = n(),
            sig = sum(SIGNIFICANT == "YES", na.rm = T),
            hca = sum(COULD_BE_HCA == "YES", na.rm = T),
            rel = sum(TOTAL_RELEASE, na.rm = T),
            cost = sum(TOTAL_COST_CURRENT, na.rm = T),
            fatal = sum(FATAL, na.rm = T),
            injure = sum(INJURE, na.rm = T))%>%
  ungroup()%>%
  complete(COMMODITY_RELEASED_TYPE, IYEAR, fill = list(n = 0, hca = 0,sig = 0,
                                                       rel = 0, cost = 0,
                                                       fatal = 0, injure = 0))%>%
  left_join(com_names)%>% 
  left_join(
    liqAR_fix %>%
      filter(between(REPORT_YEAR, 2014,2023))%>%
      group_by(PARTA5COMMODITY, REPORT_YEAR)%>%
      summarize(miles = sum(PARTDTOTALMILES, na.rm = T),
                hca_miles = sum(PARTBHCATOTAL, na.rm = T)),
    by = c("IYEAR" = "REPORT_YEAR", "PARTA5COMMODITY" = "PARTA5COMMODITY")
  )%>%
  #filter(!grepl("BIOFUEL", COMMODITY_RELEASED_TYPE))%>%
  ggplot(aes(x = IYEAR, y = n/(miles/1000), col = new_names))+
  geom_line(show.legend = F, linewidth = .88)+
  geom_text_repel(aes(label = str_wrap(new_names, 16), x = 2023.1),
            data = . %>% filter(IYEAR == 2023 & !grepl("Ethanol",new_names)),
            show.legend = F, hjust = 0, vjust = 0, 
            lineheight = .66, direction = "y", max.overlaps = 5,
            min.segment.length = .5,
            xlim = c(2010,2025))+
  scale_color_manual(values = pstRep)+
  scale_x_continuous(limits = c(2014, 2023.1), expand = c(0,0),
                     breaks = seq(2010,2022,2),
                     oob = function(x, ...) x)+
  scale_y_continuous(limits = c(0,3.8), expand = c(0,0))+
  coord_cartesian(clip="off")+
  theme_pst()+
  theme(plot.margin = margin(3,30,3,4, "mm"),
        plot.tag.location = "plot",
        plot.caption.position = "plot")+
  labs(y = "Incidents per 1,000 Miles", x=NULL, title = "Hazardous Liquid Incident Rate by Commodity",
       caption = "PHMSA Annual Reports, Hazardous Liquids 2010-2023",
       tag = tag)

ggsave("plots/hl_inc_rate.png", width = wdt, height = hgt)

```



```{r sig inc rate}
hl %>%
  filter(between(IYEAR, 2014,2023))%>%
  group_by(COMMODITY_RELEASED_TYPE, IYEAR) %>%
  summarize(n = n(),
            sig = sum(SIGNIFICANT == "YES", na.rm = T),
            hca = sum(COULD_BE_HCA == "YES", na.rm = T),
            rel = sum(TOTAL_RELEASE, na.rm = T),
            cost = sum(TOTAL_COST_CURRENT, na.rm = T),
            fatal = sum(FATAL, na.rm = T),
            injure = sum(INJURE, na.rm = T))%>%
  ungroup()%>%
  complete(COMMODITY_RELEASED_TYPE, IYEAR, fill = list(n = 0, hca = 0,sig = 0,
                                                       rel = 0, cost = 0,
                                                       fatal = 0, injure = 0))%>%
  left_join(com_names)%>% 
  left_join(
    liqAR_fix %>%
      filter(between(REPORT_YEAR, 2014,2023))%>%
      group_by(PARTA5COMMODITY, REPORT_YEAR)%>%
      summarize(miles = sum(PARTDTOTALMILES, na.rm = T),
                hca_miles = sum(PARTBHCATOTAL, na.rm = T)),
    by = c("IYEAR" = "REPORT_YEAR", "PARTA5COMMODITY" = "PARTA5COMMODITY")
  )%>%
  #filter(!grepl("BIOFUEL", COMMODITY_RELEASED_TYPE))%>%
  ggplot(aes(x = IYEAR, y = sig/(miles/1000), col = new_names))+
  geom_line(show.legend = F, linewidth = .85)+
  geom_text_repel(aes(label = str_wrap(new_names, 16), x = 2023.1),
            data = . %>% filter(IYEAR == 2023 & !grepl("Ethanol",new_names)),
            show.legend = F, hjust = 0, vjust = .66, 
            lineheight = .66, direction = "y", max.overlaps = 5,
            min.segment.length = .5,
            xlim = c(2010,2025))+
  scale_color_manual(values = pstRep)+
  scale_x_continuous(limits = c(2014, 2023.1), expand = c(0,0),
                     breaks = seq(2010,2022,2),
                     oob = function(x, ...) x)+
  scale_y_continuous(limits = c(0,1.4), expand = c(0,0))+
  coord_cartesian(clip="off")+
  theme_pst()+
  theme(plot.margin = margin(3,30,3,4, "mm"),
        plot.tag.location = "plot",
        plot.caption.position = "plot")+
  labs(y = "Significant Incidents per 1,000 Miles", x=NULL, title = "Hazardous Liquid Significant Incident Rate by Commodity",
       caption = "PHMSA Annual Reports, Hazardous Liquids 2010-2022",
       tag = tag)

ggsave("plots/hl_sig_rate.png", width = wdt, height = hgt)

```

```{r hca inc rate}
hl %>%
  filter(between(IYEAR, 2014,2023))%>%
  group_by(COMMODITY_RELEASED_TYPE, IYEAR) %>%
  summarize(n = n(),
            sig = sum(SIGNIFICANT == "YES", na.rm = T),
            hca = sum(COULD_BE_HCA == "YES", na.rm = T),
            rel = sum(TOTAL_RELEASE, na.rm = T),
            cost = sum(TOTAL_COST_CURRENT, na.rm = T),
            fatal = sum(FATAL, na.rm = T),
            injure = sum(INJURE, na.rm = T))%>%
  ungroup()%>%
  complete(COMMODITY_RELEASED_TYPE, IYEAR, fill = list(n = 0, hca = 0,sig = 0,
                                                       rel = 0, cost = 0,
                                                       fatal = 0, injure = 0))%>%
  left_join(com_names)%>% 
  left_join(
    liqAR_fix %>%
      filter(between(REPORT_YEAR, 2014,2023))%>%
      group_by(PARTA5COMMODITY, REPORT_YEAR)%>%
      summarize(miles = sum(PARTDTOTALMILES, na.rm = T),
                hca_miles = sum(PARTBHCATOTAL, na.rm = T)),
    by = c("IYEAR" = "REPORT_YEAR", "PARTA5COMMODITY" = "PARTA5COMMODITY")
  )%>% 
  filter(!grepl("BIOFUEL", COMMODITY_RELEASED_TYPE))%>%
  ggplot(aes(x = IYEAR, y = hca/(hca_miles/1000), col = new_names))+
  geom_line(show.legend = F, linewidth = .8)+
  geom_text_repel(aes(label = str_wrap(new_names, 16), x = 2023.1),
            data = . %>% filter(IYEAR == 2023 & !grepl("Ethanol",new_names)),
            show.legend = F, hjust = 0, vjust = 0, 
            lineheight = .66, direction = "y", max.overlaps = 5,
            min.segment.length = .5,
            xlim = c(2010,2025))+
  scale_color_manual(values = pstRep)+
  scale_x_continuous(limits = c(2014, 2023.1), expand = c(0,0),
                     breaks = seq(2010,2022,2),
                     oob = function(x, ...) x)+
  scale_y_continuous(limits = c(0,6.1), expand = c(0,0))+
  coord_cartesian(clip="off", xlim = c(2014,2023.1))+
  theme_pst()+
  theme(plot.margin = margin(3,30,3,4, "mm"),
        plot.tag.location = "plot",
        plot.caption.position = "plot")+
  labs(y = "Incidents per 1,000 Miles", x=NULL, title = "Hazardous Liquid High Consequence Incident Rate by Commodity",
       caption = "PHMSA Annual Reports, Hazardous Liquids 2010-2022",
       tag = tag)

ggsave("plots/hl_hca_rate.png", width = wdt, height = hgt)

```

```{r}
voi = c("ir", "sir","injure","fatal", "relp", "costp")

hl %>%
  filter(between(IYEAR, 2014,2023))%>%
  group_by(COMMODITY_RELEASED_TYPE, IYEAR) %>%
  summarize(n = n(),
            sig = sum(SIGNIFICANT == "YES", na.rm = T),
            hca = sum(COULD_BE_HCA == "YES", na.rm = T),
            rel = sum(TOTAL_RELEASE, na.rm = T),
            cost = sum(TOTAL_COST_CURRENT, na.rm = T),
            fatal = sum(FATAL, na.rm = T),
            injure = sum(INJURE, na.rm = T))%>%
  ungroup()%>% 
  complete(COMMODITY_RELEASED_TYPE, IYEAR, fill = list(n = 0, hca = 0,sig = 0,
                                                       sigp = 0, 
                                                       rel = 0, cost = 0,
                                                       fatal = 0, injure = 0))%>%
  left_join(com_names)%>% 
  left_join(
    liqAR_fix %>%
      filter(between(REPORT_YEAR, 2014,2023))%>%
      group_by(PARTA5COMMODITY, REPORT_YEAR)%>%
      summarize(miles = sum(PARTDTOTALMILES, na.rm = T),
                hca_miles = sum(PARTBHCATOTAL, na.rm = T)),
    by = c("IYEAR" = "REPORT_YEAR", "PARTA5COMMODITY" = "PARTA5COMMODITY")
  ) %>%
  mutate(ir = n / (miles/1000),
         sir = sig / (miles/1000),
         hcar = hca / (hca_miles/1000)) %>% view
  group_by(new_names)%>%
  summarise(across(n:injure, ~sum(.x,na.rm = T), .names = "{.col}_orig"),
            across(ir:hcar, ~ mean(.x,na.rm = T), .names = "{.col}_orig"),
            miles_orig = miles[IYEAR == 2023])%>%
  mutate(sigp_orig = sig_orig/n_orig,
         costp_orig = cost_orig/n_orig,
         relp_orig = rel_orig/n_orig)%>%
  ungroup()%>%
  mutate(across(ends_with("_orig"), ~(.x - min(.x))/(max(.x)- min(.x)), .names = "{.col}_per"))%>%
  rename_with(~str_replace(., "orig_", ""))%>%
  pivot_longer(-new_names,
               names_to = c("var", ".value"),
               names_sep = "_") %>% 
  filter(var%in%voi)%>%
  mutate(val_lab = case_when(
    var == "costp" ~ scales::dollar(orig, scale = .001, 
                                    accuracy = 1, suffix = "K"),
    var == "relp" ~ scales::comma(orig, scale = .001, 
                                    accuracy = 1, suffix = "K"),
    var == "miles" & orig < 1000 ~ as.character(round(orig, 0)),
    var == "miles" & orig >= 1000 ~ scales::comma(orig, scale = .001, 
                                    accuracy = 1, suffix = "K"),
    var %in% c("ir", "sir") ~ as.character(round(orig, 1)),
    .default = as.character(orig)
  ),
  var = factor(var, levels = rev(voi),
               labels = rev(c( "Rate", "Sig. Rate",
                          "Injuries", "Fatalities", "Release per", 
                          "Cost per"))))%>%
  ggplot(aes(x = var, y = per, fill = new_names, group = new_names))+
  geom_col(position = position_dodge(width = .85), width = .85)+
  geom_text(aes(label = val_lab, 
                y = ifelse(per>.5, per-.02, per+.02),
                hjust = ifelse(per>.5,1, 0),
                col = ifelse(per>.5,"black", "white" ),
                group = new_names,
                x = var), 
            position = position_dodge(width = .85),
            show.legend = F, fontface = "bold", size = 3.3)+
  scale_fill_manual(values = pstRep, name = NULL)+
  scale_color_manual(values = c( "#fffff0", richblk))+
  scale_y_continuous(breaks = seq(0,1,.25), labels = c("Min", "25%",
                                                       "50%", "75%", "Max"))+
  coord_flip()+
  theme_pst_flip()+
  theme(axis.line.y = element_blank(),
        axis.text.y = element_text(size = bs, color = richblk))+
  labs(title = "HL Incident Summary by Commodity",
       subtitle = "Min-Max Normalization of Impacts",
       tag = tag, caption = "PHMSA Flagged Files & Annual Reports, 2024",
       y = NULL)
  
  
ggsave("plots/summary.png", width = wdt, height = wdt/1.33)

```

```{r}
hl %>%
  filter(between(IYEAR, 2014,2023))%>%
  left_join(com_names)%>%
  count(new_names, CAUSE) %>% 
  complete(new_names, CAUSE, fill = list(n = 0))%>%
  group_by(new_names)%>%
  mutate(total = sum(n),
         maxn = max(n))%>%
    filter(total > 1)%>%
  ungroup()%>%
  mutate(per = n/total,
         bold_bool = (n == maxn))%>%
  ggplot(aes(x = CAUSE, y = new_names, fill = per, label = scales::percent(per, accuracy = .1)))+
  geom_tile(height = .9, width = .9)+
  geom_text(aes(fontface = ifelse(bold_bool, "bold", "plain"),
                color = ifelse(per > .44, "white", "black")),
            show.legend = F)+
  scale_color_manual(values =c( richblk, "#fffff0"))+
  scale_fill_gradient(low = muted(liteGreen, l = 95, c = 3), 
                   high = midBlue, limits = c(0,.7), 
                   labels = scales::label_percent(), 
                   name = NULL, breaks = c(.1,.3,.5,.7))+
  scale_x_discrete(position = "top", name = NULL,
                   labels = function(x) str_to_title(str_wrap(x, 18)))+
  scale_y_discrete(labels = function(x) str_wrap(x, 18), name = NULL)+
  theme_pst()+
  theme(axis.text.x.top = element_text(angle = -45, vjust = 0.5, 
                                       hjust = 1, size = bs, color = richblk),
        axis.text.y = element_text(size = bs, color = richblk),
        axis.line.x = element_blank(),
        axis.line.y = element_blank(),
        panel.grid.major.y = element_blank(),
        axis.ticks = element_blank(),
        axis.ticks.y = element_blank(),
        legend.position = "right",
        legend.direction = "vertical",
        legend.background = element_blank())+
  labs(title = "HL Incident Causes by Commodity",
       tag = tag, caption = "PHMSA Flagged Files, 2024")
ggsave("plots/all_cause.png", width = wdt, height = hgt)

hl %>%
  filter(between(IYEAR, 2014,2023), SIGNIFICANT == "YES")%>%
  left_join(com_names)%>%
  count(new_names, CAUSE) %>% 
  complete(new_names, CAUSE, fill = list(n = 0))%>%
  group_by(new_names)%>%
  mutate(total = sum(n),
         maxn = max(n))%>%
    filter(total > 1)%>%
  ungroup()%>%
  mutate(per = n/total,
         bold_bool = (n == maxn))%>%
  ggplot(aes(x = CAUSE, y = new_names, fill = per, label = scales::percent(per, accuracy = .1)))+
  geom_tile(height = .9, width = .9)+
  geom_text(aes(fontface = ifelse(bold_bool, "bold", "plain"),
                color = ifelse(per > .44, "white", "black")),
            show.legend = F)+
  scale_color_manual(values =c( richblk, "#fffff0"))+
  scale_fill_gradient(low = muted(liteGreen, l = 95, c = 3), 
                   high = midBlue, limits = c(0,.7), 
                   labels = scales::label_percent(), 
                   name = NULL, breaks = c(.1,.3,.5,.7))+
  scale_x_discrete(position = "top", name = NULL,
                   labels = function(x) str_to_title(str_wrap(x, 18)))+
  scale_y_discrete(labels = function(x) str_wrap(x, 18), name = NULL)+
  theme_pst()+
  theme(axis.text.x.top = element_text(angle = -45, vjust = 0.5, 
                                       hjust = 1, size = bs, color = richblk),
        axis.text.y = element_text(size = bs, color = richblk),
        axis.line.x = element_blank(),
        axis.line.y = element_blank(),
        panel.grid.major.y = element_blank(),
        axis.ticks = element_blank(),
        axis.ticks.y = element_blank(),
        legend.position = "right",
        legend.direction = "vertical",
        legend.background = element_blank())+
  labs(title = "HL Significant Incident Causes",
       subtitle = "Commodities with >1 Significant Incident",
       tag = tag, caption = "PHMSA Flagged Files, 2024")
ggsave("plots/sig_cause.png", width = wdt, height = hgt)

```

```{r}
hl %>%
  filter(between(IYEAR, 2014,2023))%>%
  left_join(com_names)%>%
  count(new_names, SYSTEM_PART_INVOLVED) %>% 
  complete(new_names, SYSTEM_PART_INVOLVED, fill = list(n = 0))%>%
  group_by(new_names)%>%
  mutate(total = sum(n),
         maxn = max(n))%>%
    filter(total > 1)%>%
  ungroup()%>%
  mutate(per = n/total,
         bold_bool = (n == maxn))%>%
  ggplot(aes(x = SYSTEM_PART_INVOLVED, y = new_names, fill = per, label = scales::percent(per, accuracy = .1)))+
  geom_tile(height = .9, width = .9)+
  geom_text(aes(fontface = ifelse(bold_bool, "bold", "plain"),
                color = ifelse(per > .49, "white", "black")),
            show.legend = F)+
  scale_color_manual(values =c( richblk, "#fffff0"))+
  scale_fill_gradient(low = muted(liteGreen, l = 95, c = 3), 
                   high = midBlue, limits = c(0,.85), 
                   labels = scales::label_percent(), 
                   name = NULL, breaks = c(0,.2,.4,.6,.8))+
  scale_x_discrete(name = NULL,labels = function(x)
    str_trunc(str_to_title(str_wrap(x, 21)),39), position = "top")+
  scale_y_discrete(labels = function(x) str_wrap(x, 16), name = NULL)+
  theme_pst()+
  theme(axis.text.x.top = element_text(size = bs,angle = -45,
                                       hjust = 1,color = richblk),
        axis.text.y = element_text(size = bs, color = richblk),
        axis.line.x = element_blank(),
        axis.line.y = element_blank(),
        panel.grid.major.y = element_blank(),
        axis.ticks = element_blank(),
        axis.ticks.y = element_blank(),
        legend.position = "right",
        legend.direction = "vertical",
        legend.background = element_blank())+
  labs(title = "HL Incident Part Failures by Commodity",
       tag = tag, caption = "PHMSA Flagged Files, 2024")
ggsave("plots/all_part.png", width = wdt, height = hgt)

hl %>%
  filter(between(IYEAR, 2014,2023), SIGNIFICANT == "YES")%>%
  left_join(com_names)%>%
  count(new_names, SYSTEM_PART_INVOLVED) %>% 
  complete(new_names, SYSTEM_PART_INVOLVED, fill = list(n = 0))%>%
  group_by(new_names)%>%
  mutate(total = sum(n),
         maxn = max(n))%>%
    filter(total > 1)%>%
  ungroup()%>%
  mutate(per = n/total,
         bold_bool = (n == maxn))%>%
  ggplot(aes(x = SYSTEM_PART_INVOLVED, y = new_names, fill = per, label = scales::percent(per, accuracy = .1)))+
  geom_tile(height = .9, width = .9)+
  geom_text(aes(fontface = ifelse(bold_bool, "bold", "plain"),
                color = ifelse(per > .49, "white", "black")),
            show.legend = F)+
  scale_color_manual(values =c( richblk, "#fffff0"))+
  scale_fill_gradient(low = muted(liteGreen, l = 95, c = 3), 
                   high = midBlue, limits = c(0,.85), 
                   labels = scales::label_percent(), 
                   name = NULL, breaks = c(0,.2,.4,.6,.8))+
  scale_x_discrete(name = NULL,labels = function(x)
    str_trunc(str_to_title(str_wrap(x, 21)),39), position = "top")+
  scale_y_discrete(labels = function(x) str_wrap(x, 16), name = NULL)+
  theme_pst()+
  theme(axis.text.x.top = element_text(size = bs,angle = -45, 
                                       hjust = 1, color = richblk),
        axis.text.y = element_text(size = bs, color = richblk),
        axis.line.x = element_blank(),
        axis.line.y = element_blank(),
        panel.grid.major.y = element_blank(),
        axis.ticks = element_blank(),
        axis.ticks.y = element_blank(),
        legend.position = "right",
        legend.direction = "vertical",
        legend.background = element_blank())+
  labs(title = "HL Significant Incident Part Failures",
       subtitle = "Commodities with >1 Significant Incident",
       tag = tag, caption = "PHMSA Flagged Files, 2024")
ggsave("plots/sig_part.png", width = wdt, height = hgt)

```


```{r}
hl %>%
   filter(between(IYEAR, 2014, 2023),
         ON_OFF_SHORE == "ONSHORE",
         #SIGNIFICANT == "YES",
        # grepl("INCLUDING VALVE SITES",SYSTEM_PART_INVOLVED)
         )%>%
  filter(!is.na(ON_SITE_DATETIME))%>%
  mutate(onsitediff = seconds_to_period( ON_SITE_DATETIME - INCIDENT_IDENTIFIED_DATETIME) ,
         shutdowninc = seconds_to_period(SHUTDOWN_DATETIME - LOCAL_DATETIME),
         shutdowndiff = seconds_to_period(SHUTDOWN_DATETIME - INCIDENT_IDENTIFIED_DATETIME)) %>%
  #filter(COMMODITY_RELEASED_TYPE == "CO2 (CARBON DIOXIDE)")%>%
  select(MDY, NAME.x,cleanLoc, ON_SITE_DATETIME, SHUTDOWN_DATETIME,
         INCIDENT_IDENTIFIED_DATETIME, ACCIDENT_IDENTIFIER,
         ACCIDENT_DETAILS, COMMODITY_RELEASED_TYPE,
         #ends_with("DATETIME"),
         TOTAL_RELEASE, onsitediff, shutdowndiff, shutdowninc)%>% #view
  select(COMMODITY_RELEASED_TYPE,INCIDENT_IDENTIFIED_DATETIME, SHUTDOWN_DATETIME,onsitediff, shutdowndiff, shutdowninc) %>%
  # filter(!is.na(onsitediff))%>%
 filter(onsitediff >= seconds(0),
        shutdowndiff >= seconds(0)) %>%
  mutate(onsitediff = period_to_seconds(onsitediff),
         shutdowndiff = period_to_seconds(shutdowndiff)) %>% 
  left_join(com_names)%>%
  mutate(new_names = factor(new_names, 
                            levels = c("CO2", "HVL", "Petrol Product (non-HVL)",
                                       "Crude Oil", "Fuel Grade Ethanol")))%>%
  #filter(!grepl("BIO", COMMODITY_RELEASED_TYPE))%>%
  ggplot(aes(x = fct_rev(new_names), y = shutdowndiff, col = new_names))+
  geom_boxplot(show.legend = F, linewidth = .8)+
 scale_y_continuous(trans = "pseudo_log",
                     breaks = c(0, 60,3600, 86400, 604800, 2629800, 7889400 ),
                     labels = c("0", "Minute", "Hour", "Day", 
                                "Week", "Month", "Qrt."),
                     minor_breaks = c(30, 1800, 43200, 302400, 1296000, 
                                      3944700))+
  scale_color_manual(values = pstRep)+
   scale_x_discrete(labels = function(x) str_wrap(x, 16), name = NULL)+
  coord_flip()+
  theme_pst_flip()+
  theme(axis.text.y = element_text(size = bs, color = richblk),
        axis.text.x = element_text(size = bs))+
  labs(title = "Shutdown Time of Onshore Pipeline Incidents by Commodity",
       subtitle = "All system parts, excluding times less than 0 seconds",
       tag = tag, caption = "PHMSA Flagged Files, 2024", y = NULL)

ggsave("plots/all_box.png", width = wdt, height = hgt)

hl %>%
   filter(between(IYEAR, 2014, 2023),
         ON_OFF_SHORE == "ONSHORE",
         #SIGNIFICANT == "YES",
        grepl("INCLUDING VALVE SITES",SYSTEM_PART_INVOLVED)
         )%>%
  filter(!is.na(ON_SITE_DATETIME))%>%
  mutate(onsitediff = seconds_to_period( ON_SITE_DATETIME - INCIDENT_IDENTIFIED_DATETIME) ,
         shutdowninc = seconds_to_period(SHUTDOWN_DATETIME - LOCAL_DATETIME),
         shutdowndiff = seconds_to_period(SHUTDOWN_DATETIME - INCIDENT_IDENTIFIED_DATETIME)) %>%
  #filter(COMMODITY_RELEASED_TYPE == "CO2 (CARBON DIOXIDE)")%>%
  select(MDY, NAME.x,cleanLoc, ON_SITE_DATETIME, SHUTDOWN_DATETIME,
         INCIDENT_IDENTIFIED_DATETIME, ACCIDENT_IDENTIFIER,
         ACCIDENT_DETAILS, COMMODITY_RELEASED_TYPE,
         #ends_with("DATETIME"),
         TOTAL_RELEASE, onsitediff, shutdowndiff, shutdowninc)%>% #view
  select(COMMODITY_RELEASED_TYPE,INCIDENT_IDENTIFIED_DATETIME, SHUTDOWN_DATETIME,onsitediff, shutdowndiff, shutdowninc) %>%
  # filter(!is.na(onsitediff))%>%
 filter(onsitediff >= seconds(0),
        shutdowndiff >= seconds(0)) %>%
  mutate(onsitediff = period_to_seconds(onsitediff),
         shutdowndiff = period_to_seconds(shutdowndiff)) %>% 
  left_join(com_names)%>%
  mutate(new_names = factor(new_names, 
                            levels = c("CO2", "HVL", "Petrol Product (non-HVL)",
                                       "Crude Oil", "Fuel Grade Ethanol")))%>%
  filter(!grepl("BIO", COMMODITY_RELEASED_TYPE))%>%
  ggplot(aes(x = fct_rev(new_names), y = shutdowndiff, col = new_names))+
  geom_boxplot(show.legend = F, linewidth = .8)+
 scale_y_continuous(trans = "pseudo_log",
                     breaks = c(0, 60,3600, 86400, 604800, 2629800, 7889400 ),
                     labels = c("0", "Minute", "Hour", "Day", 
                                "Week", "Month", "Qrt."),
                     minor_breaks = c(30, 1800, 43200, 302400, 1296000, 
                                      3944700))+
  scale_color_manual(values = pstRep)+
   scale_x_discrete(labels = function(x) str_wrap(x, 16), name = NULL)+
  coord_flip()+
  theme_pst_flip()+
  theme(axis.text.y = element_text(size = bs, color = richblk),
        axis.text.x = element_text(size = bs))+
  labs(title = "Shutdown Time of Onshore Pipeline Incidents by Commodity",
       subtitle = "Incidents on pipelines, including valve sites alone",
       tag = tag, caption = "PHMSA Flagged Files, 2024", y = NULL)

ggsave("plots/pipe_box.png", width = wdt, height = hgt)
```

```{r}

hl %>%
   filter(between(IYEAR, 2014, 2023),
         ON_OFF_SHORE == "ONSHORE",
         #SIGNIFICANT == "YES",
       # grepl("INCLUDING VALVE SITES",SYSTEM_PART_INVOLVED)
         )%>%
  filter(!is.na(ON_SITE_DATETIME))%>%
  mutate(onsitediff = seconds_to_period( ON_SITE_DATETIME - INCIDENT_IDENTIFIED_DATETIME) ,
         shutdowninc = seconds_to_period(SHUTDOWN_DATETIME - LOCAL_DATETIME),
         shutdowndiff = seconds_to_period(SHUTDOWN_DATETIME - INCIDENT_IDENTIFIED_DATETIME)) %>%
  #filter(COMMODITY_RELEASED_TYPE == "CO2 (CARBON DIOXIDE)")%>%
  select(MDY,IYEAR, NAME.x,cleanLoc, ON_SITE_DATETIME, SHUTDOWN_DATETIME,
         INCIDENT_IDENTIFIED_DATETIME, ACCIDENT_IDENTIFIER,
         ACCIDENT_DETAILS, COMMODITY_RELEASED_TYPE,
         #ends_with("DATETIME"),
         TOTAL_RELEASE, onsitediff, shutdowndiff, shutdowninc)%>% #view
  select(IYEAR, COMMODITY_RELEASED_TYPE,INCIDENT_IDENTIFIED_DATETIME, SHUTDOWN_DATETIME,onsitediff, shutdowndiff, shutdowninc) %>%
  # filter(!is.na(onsitediff))%>%
 # filter(onsitediff >= seconds(0),
 #        shutdowndiff >= seconds(0)) %>%
  mutate(onsitediff = period_to_seconds(onsitediff),
         shutdowndiff = period_to_seconds(shutdowndiff)) %>% 
  left_join(com_names)%>% 
  mutate(new_names = factor(new_names, 
                            levels = c("CO2", "HVL", "Petrol Product (non-HVL)",
                                       "Crude Oil", "Fuel Grade Ethanol")))%>% view
  ggplot(aes(x=shutdowndiff))+
  geom_histogram(fill = liteGreen)+
  #geom_density(linewidth = 1, col = midBlue)+
  scale_x_continuous(trans = "pseudo_log",
                     breaks = c(-2629800,-86400,-1800,0, 
                                1800,86400, 2629800 ),
                     labels = c("-Month","-Day","-Hour","0",  
                                "Hour","Day","Month"),
                     minor_breaks = c(-1296000,-302400 ,-43200,
                                      43200, 302400, 1296000))+
  scale_y_continuous(limits = c(-10,700), expand = c(0,0))+
  theme_pst(12)+
  theme(axis.line.x = element_blank(),
        axis.text.x = element_text(angle = 30, hjust = 1.1, size = 7.5, vjust = 1.1))+
  labs(title = NULL, y = "Incidents", x = "Shutdown Time")


ggsave("plots/time_dist.png", width = 3, height = 3/1.62)

```


```{r}
hl %>%
   filter(between(IYEAR, 2014, 2023),
         ON_OFF_SHORE == "ONSHORE",
         #SIGNIFICANT == "YES",
       # grepl("INCLUDING VALVE SITES",SYSTEM_PART_INVOLVED)
         )%>%
  filter(!is.na(ON_SITE_DATETIME))%>%
  mutate(onsitediff = seconds_to_period( ON_SITE_DATETIME - INCIDENT_IDENTIFIED_DATETIME) ,
         shutdowninc = seconds_to_period(SHUTDOWN_DATETIME - LOCAL_DATETIME),
         shutdowndiff = seconds_to_period(SHUTDOWN_DATETIME - INCIDENT_IDENTIFIED_DATETIME)) %>%
  #filter(COMMODITY_RELEASED_TYPE == "CO2 (CARBON DIOXIDE)")%>%
  select(MDY,IYEAR, NAME.x,cleanLoc, ON_SITE_DATETIME, SHUTDOWN_DATETIME,
         INCIDENT_IDENTIFIED_DATETIME, ACCIDENT_IDENTIFIER,
         ACCIDENT_DETAILS, COMMODITY_RELEASED_TYPE,
         #ends_with("DATETIME"),
         TOTAL_RELEASE, onsitediff, shutdowndiff, shutdowninc)%>% #view
  select(IYEAR, COMMODITY_RELEASED_TYPE,INCIDENT_IDENTIFIED_DATETIME, SHUTDOWN_DATETIME,onsitediff, shutdowndiff, shutdowninc) %>%
  # filter(!is.na(onsitediff))%>%
 # filter(onsitediff >= seconds(0),
 #        shutdowndiff >= seconds(0)) %>%
  mutate(onsitediff = period_to_seconds(onsitediff),
         shutdowndiff = period_to_seconds(shutdowndiff)) %>% 
  left_join(com_names)%>% 
  mutate(new_names = factor(new_names, 
                            levels = c("CO2", "HVL", "Petrol Product (non-HVL)",
                                       "Crude Oil", "Fuel Grade Ethanol")))%>%
  mutate(neg = shutdowndiff <0 )%>%
  count(IYEAR, neg) %>%
  drop_na()%>%
  group_by(IYEAR) %>%
  summarize(total = sum(n),
            neg = sum(n[neg==TRUE], na.rm = T))%>%
  ungroup()%>%
  mutate(per = neg/total)%>%
  ggplot(aes(x = IYEAR, y = per))+
  geom_line(color = liteGreen, linewidth = 1)+
  theme_pst(12)+
  scale_y_continuous(limits = c(0,.17), labels = scales::label_percent())+
  labs(y = "% Reported < 0 sec.", x = NULL)


ggsave("plots/time_trend.png", width = 3, height = 3/1.62)


```

